[package]
name = "league-archive"
version = "0.1.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]

[dependencies]
clap = "2.2.4"
rusqlite = "0.6.0"

[dependencies.mysql]
version = "2.2.1"
default-features = false
features = []
